title: The Fox Den
description: A loosely organized collection of notes, guides, and the occasional rant.
theme: jekyll-theme-modernist
show_downloads: false

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
